### ISSUE TITLE
Midi Upgrade for HD Audio Waves Update Code

### ISSUE THREAD

**Issue by dogansese** [MrDham/OpenTheremin_V3_with_MIDI#22]
Hi, thank you for your great work for midi fuunction added to code! Can you please add midi code to  new updated code as "High Definition Audio" at April 2020? That would be great to play it as midi and HD Audio waves together.

**Comment by MrDham** [comment]
Hi, I already added all the changes corresponding to "HD audio" to latest version of Open Theremin with MIDI (V2.3). 
So, if you use this repository, you can already use midi and HD Audio waves together.

**Comment by MrDham** [comment]
I hope that the previous comment answered to your question. If not, please comment. Else, I'll close the issue in a few days.

**Comment by dogansese** [comment]
Hi Dham. Thank you for answer. Really sorry that i wasn't able to reach internet. I got what i need now. Thank you so much for your great work.

**Comment by MrDham** [comment]
No problem :-)
We all have to disconect from internet from time to time... That's the real life.  

Thanks for your comments, it's always good to hear from some users.
