### ISSUE TITLE
ROD CC instead of pitchbend

### ISSUE THREAD

**Issue by patricksebastien** [MrDham/OpenTheremin_V3_with_MIDI#24]
Volume antenna is working (I receive CC 7 in my software), ROD antenna is working too sending as pitchbend midi message. How to change that to CC from 0 - 127 depending on the distance?

Thank you!

**Comment by MrDham** [comment]
It already exists :-)

In the readme file you can read:

"MIDI CC from Pitch antenna (Rod) have 14 Bit resolution when applicable. Example of application: you can create a software synth controled by CC7 for volume and CC16 (MSB) - CC48 (LSB) for pitch without using Note On/Off and Pitch Bend messages."

The trick is to put "Tigger Volume / Velocity" at maximum so as Note On/Off and Pitch Bend messages are not sent. 
Then choose appropriate CC for the rod .


See the quick user guide: https://raw.githubusercontent.com/MrDham/OpenTheremin_V3_with_MIDI/master/Quick%20guide%20open%20theremin%20midi.bmp 

I use this configuration with https://github.com/MrDham/Pure-Data-FM-Ribbon-Synth


Does it answer to the question ?

**Comment by patricksebastien** [comment]
Exactly what I needed + a pd patch! Wonderful work. Thank you very much!
